name: Build and Deploy
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          pwd
          whoami

      - name: Install
        run: |
          sudo apt-get install -y asciidoctor
          gem install asciidoctor-pdf --user-install
          ls -la /home/runner/.gem/ruby
          gem install asciidoctor-epub3 --user-install

      - name: Build
        run: |
          asciidoctor pcct.adoc -o index.html -D build
          asciidoctor-pdf pcct.adoc -D build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build