name: Build and Deploy
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
env:
  source_file_name: pcct
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          sudo gem install asciidoctor asciidoctor-pdf asciidoctor-epub3

      - name: Build
        run: |
          asciidoctor ${{ env.source_file_name }}.adoc -o index.html -D build
          asciidoctor-pdf ${{ env.source_file_name }}.adoc -D build
          asciidoctor-epub3 ${{ env.source_file_name }}.adoc -D build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build